name: battlity
description: Battlity
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  vk_bridge: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
